source ENV['GEM_SOURCE'] || "http://ec2-52-55-30-243.compute-1.amazonaws.com:9292/"

gem 'json', :require => false

if facterversion = ENV['FACTER_GEM_VERSION']
  gem 'facter', facterversion, :require => false
else
  gem 'facter', :require => false
end
